### GET Elevator Status
GET http://localhost:8080/api/v1/elevator

### POST Make an Elevator Step
POST http://localhost:8080/api/v1/elevator/step?numberOfSteps=1

### POST Pickup Request
POST http://localhost:8080/api/v1/elevator/pickup
Content-Type: application/json

{
  "currentFloor": 9,
  "destinationFloor": 7
}

<> 2025-11-28T221714.200.json
